name: mixins
description: Mixins is a package for shortening the use of some widgets or properties.
version: 0.0.10
homepage: https://github.com/ashtav/mixins

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  intl: ^0.17.0
  path_provider: ^2.0.11
  stack_trace: ^1.10.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: null